<a href="https://colab.research.google.com/github/theakash07/100_Days_Machine_Learning/blob/main/HousePricePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Housing.csv')

In [4]:
df.head(5)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [ ]:
df.describe()

In [8]:
df['area'].unique()

array([ 7420,  8960,  9960,  7500,  8580, 16200,  8100,  5750, 13200,
        6000,  6550,  3500,  7800,  6600,  8500,  4600,  6420,  4320,
        7155,  8050,  4560,  8800,  6540,  8875,  7950,  5500,  7475,
        7000,  4880,  5960,  6840,  7482,  9000,  6360,  6480,  4300,
        7440,  6325,  5150, 11440,  7680,  8880,  6240, 11175,  7700,
       12090,  4000,  5020,  4040,  4260,  6500,  5700, 10500,  3760,
        8250,  6670,  3960,  7410,  5000,  6750,  4800,  7200,  4100,
        6400,  6350,  4500,  5450,  3240,  6615,  8372,  9620,  6800,
        8000,  6900,  3700,  7020,  7231,  6254,  7320,  6525, 15600,
        7160, 11460,  5828,  5200,  5400,  4640,  5800,  6660,  4700,
        5136,  4400,  3300,  3650,  6100,  2817,  7980,  3150,  6210,
        6825,  6710,  6450, 10269,  8400,  5300,  3800,  9800,  8520,
        6050,  7085,  3180,  3410,  3000, 11410,  5720,  3540,  7600,
       10700,  8150,  4410,  7686,  2800,  5948,  4200,  4520,  4095,
        4120,  4770,  6300,  2970,  6720,  4646, 12900,  3420,  4995,
        4350,  4160,  6040,  6862,  4815,  9166,  6321, 10240,  6440,
        5170,  3630,  9667,  3745,  3880,  5680,  2870,  5010,  4510,
        3840,  3640,  2550,  5320,  5360,  3520,  4990,  3510,  3450,
        9860,  5885,  3162,  3750,  3968,  4900,  2880,  4920,  4950,
        3900,  1905,  4075,  4032, 10360,  3400,  2175,  4360,  7770,
        6650,  2787,  5040,  5850,  2610,  2953,  2747,  2325,  4079,
        2145,  4840,  4080,  4046,  4632,  5985,  6060,  3600,  3680,
        5600,  5900,  4992,  4340,  3460,  4050,  7260,  3290,  3816,
        8080,  3780,  7152,  3850,  2015,  2176,  3350,  4820,  5830,
        2856,  2520,  6930,  3480,  6020,  3584,  3120,  5640,  4280,
        3570,  4130,  2850,  2275,  4240,  2135,  3036,  3990,  7424,
        7350,  3512,  9500,  5880, 12944,  3060,  3185,  1950,  4785,
        4960,  4750,  3720,  3100,  2700,  4775,  2500,  3792,  3930,
        4370,  2684,  3986,  1650,  3069,  5495,  2398,  2160,  3090,
        2835,  5076,  4352,  3660,  3040,  2640,  2650,  3934,  2000,
        2430,  2910,  3210,  3635,  2475,  3264,  1836,  3970,  2400,
        3360,  1700,  3649,  2990,  3620])

From here ownwards delving into graphs to find the outliers and to drop it as well from the data set for better Preanalaysis.

In [ ]:
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Plot of Two Features")
plt.scatter( df['price'], df['area'], label="Feature 2")
plt.legend()

# Show the plot
plt.show()